"""empty message

Revision ID: 411c9d62adcd
Revises: 3ceb6f5c3a05
Create Date: 2019-02-17 01:21:32.841031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411c9d62adcd'
down_revision = '3ceb6f5c3a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('person1_preset', sa.String(), nullable=True))
    op.add_column('relationships', sa.Column('person2_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'person2_preset')
    op.drop_column('relationships', 'person1_preset')
    # ### end Alembic commands ###
